config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses, only: [:index, :edit, :create, :show, :new, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_one_attached :photo
  has_many :doses, dependent: :destroy
  validates :name, uniqueness: true, presence: true

  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true

  has_many :coctails, through: :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def index
    @doses = Dose.all
  end

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end

    def destroy
      @cocktail = Cocktail.find(params[:cocktail_id])
      @dose = Dose.find(params[:id])
      @dose.destroy
      redirect_to cocktail_path
    end
  end

private

def dose_params
  params.require(:dose).permit(:description, :ingredient_id)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for [@cocktail] do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>

app/views/cocktails/edit.html.erb
<%= render 'form', cocktail: @cocktail %>

app/views/cocktails/index.html.erb
<div class="container">
  <h1>Cocktail List</h1>


<div class="d-flex justify-content-around">

  <% @cocktails.each do | cocktail | %>
  <div class="">
    <div class="row">
        <div class="col">
          <div class="card-trip">
      <% if cocktail.photo.attached? %>
          <%= cl_image_tag cocktail.photo.key, height: 200, width: 400 %>
            <% end %>
      <div class="card-trip-infos">
        <div>
          <h2><%= cocktail.name %></h2>
          <%= link_to 'More details | ', cocktail_path(cocktail) %>
         <%= link_to 'Delete', cocktail_path(cocktail), method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
      </div>
    </div>
        </div>

      </div>
  </div>
<% end %>
</div>

  <div class ="new">
      <%= link_to 'New Cocktail', new_cocktail_path(@cocktail), class: "btn btn-primary" %>
  </div>

</div>

app/views/cocktails/new.html.erb
<div class="container">
  <h1>Add a new cocktail</h1>

  <%= render 'form', cocktail: @cocktail %>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <h1> <%= @cocktail.name %></h1>
  <ul>
    <% @cocktail.doses.each do |dose| %>
    <%= cl_image_tag @cocktail.photo.key, height: 200, width: 200, crop: :fill %>
    <li><%= dose.description %> - <%= dose.ingredient.name %></li>
     <i class="far fa-trash-alt"></i> <%= link_to "delete", cocktail_dose_path(@cocktail, dose), method: :delete, data: { confirm: "Are you sure?" }%>
    <% end %>
  </ul>



</div>

<%= link_to 'Back to cocktails ', cocktails_path(@cocktail), class: "btn btn-primary" %>

<%= link_to 'Add doses', new_cocktail_dose_path(@cocktail), class: "btn btn-success" %>

<%= link_to 'Edit cocktails ', edit_cocktail_path(@cocktail), class: "btn btn-warning" %>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.button :submit %>
  <% end %>

app/views/doses/new.html.erb
<div class="container">
  <h1> Add Doses</h1>

  <%= render 'form', dose: @dose %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
     <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="#">
    <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" />
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/cocktails">Home</a>
      </li>
      <li class="nav-item dropdown">
        <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
        </div>
      </li>
    </ul>
  </div>
</div>
    <%= yield %>
     <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
     <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>